
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatdb
      username: 'root'
      password: '1234'
      authentication-database: admin
  webflux:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    web:
      DEBUG